### ISSUE TITLE
City selection

### ISSUE THREAD

**Issue by MakarkinPRO** [samarthagarwal/WC-API-JS-Client#1]
How it's possible to make a city selection?

I need create correct WooCommerce site structure (I have two ways WordPress multisite or WooCommerce Vendor plugin).

What I need when user first time start the app he selecting a city (and app remebmer his choise) after he run the next time the app don't ask him to choose a city.

**Comment by abr4xas** [comment]
@MakarkinPRO localstorage (?)

**Comment by MakarkinPRO** [comment]
Any ideas of how to realize it? may code example, because we need work with several API_keys (from each store)

**Comment by samarthagarwal** [comment]
This is not related to the library,
