### ISSUE TITLE
wcapi.js shows 5 errors

### ISSUE THREAD

**Issue by engn-pradeep** [samarthagarwal/WC-API-JS-Client#2]
file wcapi.js returns 5 errors

![error](https://cloud.githubusercontent.com/assets/22033096/18282208/b042fd26-747d-11e6-81b7-dfa8c8aa97d8.png)

**Comment by samarthagarwal** [comment]
That is probably because you have written the code somewhere such that it will never be executed, may be in an `if` statement. WCAPI Library has nothing to do with this error.
