### ISSUE TITLE
$scope object is not accessible in view file.

### ISSUE THREAD

**Issue by jaydeepjivani** [samarthagarwal/WC-API-JS-Client#4]
I cant get any data in view that i'm passing in response from controller to view.

I have used like this:

```
Woocommerce.get('products/?page='+page, function(error, data, response) {
    if( response ) {
      $scope.products = response.products;
   }  
});
```

But i'm able to get this `products` object in my view file.

**Comment by samarthagarwal** [comment]
Might be an Angular issue.
