### ISSUE TITLE
Do you still maintaining this?

### ISSUE THREAD

**Issue by davidvexel** [samarthagarwal/WC-API-JS-Client#5]
Have this issue:

[$injector:unpr] Unknown provider: WPProvider <- WP <- mycontroller

Thank you! It's hard to find a good library for angular and wc api.

**Comment by samarthagarwal** [comment]
Yeah. See https://github.com/samarthagarwal/wooionic for an example on how to use this.

**Comment by davidvexel** [comment]
Great, it works awesome with your woocommerce site, but having troubles with my local, I had to replace the v3 for v1 in the url call, do I need to update my WC? I'm running 2.6.8 I guess. thanks!

**Comment by davidvexel** [comment]
Nevermind, I was using this kind of endpoint `/wp-json/wc/v1/products`.

**Comment by samarthagarwal** [comment]
The library has been updated to allow users to use the REST API v1 and v2.
